#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# -----------------------------------------------------------------------------
# Project info
# -----------------------------------------------------------------------------
# Add information for your project. The project name will be printed when running the script.
project:
    name: 'ProjectName'            # project name
    description: 'Project aim'     # project goals
    species: 'Species'             # plant species
    tissue: 'Tissue'               # type of plant tissue/organ
    stage: 'DAG'                   # developmental stage
    projection: 'Z-projection'     # type of image projection

    
# -----------------------------------------------------------------------------
# Data structure
# -----------------------------------------------------------------------------
# Define the components of your analysis, including the root folder of your data, 
# the used image type and the different conditions/genotypes/timepoints.
data: 
    root: '/'                           # root folder in which subfolders/images are stored
    file_pattern: '*.tif'               # image file pattern to detect images for analysis
    channels: ['membrane', 'filament']  # different channels used for analysis (e.g. membrane, filament)
    targets: ['AFs', 'MTs']             # filament proteins
    conditions: ['WT', 'act2-1act7-1']  # genotypes or different treatments
    timepoints: 'multiple'              # 'single' or 'multiple'

        
# -----------------------------------------------------------------------------
# Folder structure
# -----------------------------------------------------------------------------  
# Add folder structure in order of subfolders (e.g. 'AFs' > 'WT' > '12' > ...).
# Use the same keywords as in Data structure if you have different targets, conditions,
# or timepoints. You can add replicates here. If you want to auto-detect subfolders, use '[]'.
# Only add keywords that are part of your subfolder structure (if you have no timepoints, 
# don't put them here as keyword).
structure:
    targets: ['AFs', 'MTs']               # same targets as in 'Data structure'
    conditions: ['WT', 'act2-1act7-1']    #same conditions as in Data
    timepoints: [0, 12, 24, 36, 48]       # if multiple, add all timepoints here
    replicates: []                        #auto-detect


# -----------------------------------------------------------------------------
# Image resolutions (µm/px)
# ----------------------------------------------------------------------------- 
# Add the image resolution here to convert pixel values into µm. Input the resolution as µm / px.
# Define image resolutions specific for target type or for specific replicates.
resolutions:
    AFs: {WT: {'WT_1': 1.0, 'WT_2': 1.0}, act2-1act7-1: {'act2act7_1': 1.0, 'act2act7_2': 1.0}} # µm / px
    MTs: {WT: {'WT_1': 1.0, 'WT_2': 1.0}, act2-1act7-1: {'act2act7_1': 1.0, 'act2act7_2': 1.0}}  # µm / px
 
 
# -----------------------------------------------------------------------------
# Input channel data for pavement cell segmentation
# ----------------------------------------------------------------------------- 
# Define which channels (membrane or filament) should be used for the analysis. Add the string
# to identify the channels. If set to None, this channel will not be used.
inputChannel:
    AFs: {'membrane': 'C1', 'filament': 'C2'}
    MTs: {'membrane': 'membrane', 'filament': None}
             

# -----------------------------------------------------------------------------
# Selected cells for analysis
# -----------------------------------------------------------------------------
# If specific cells should be used for the analysis, add them here. If you don't 
# want to all cells, write:
# cells: None
cells:
    AFs:
        WT:
            0: 
                R1: '[1:24]'          # you can use ':' to indicate ranges
                R2: '[2, 5, (9, 11)]' # use '()' to indicate cells that should be merged into one (e.g. stomata or segmentation errors) 
                R3: '[4, 6, 8]'
                
            12: 
                R1: '[]'                  # use empty brackets to exclude all cells
                R2: '[(1, 4), 5:8, 11]'   # combine ranges, merged cells and single cells


         
# -----------------------------------------------------------------------------
# Manual changes for pavement cell segmentation
# -----------------------------------------------------------------------------
# Indicate here if manual changes have to be added, e.g. to do manual thresholding.
#
# sigmaGauss: sigma for Gaussian filter [0-10], default: 1.0
# sigmaTube: sigma for tube filter [0-10], default: 3.0
# otsuMethod: choose otsu method for thresholding ['otsu', 'multiotsu'], default: 'otsu'
# manualThreshold: manual threshold for binarization [0-256], default: None
# sizeObject: size of small objects to remove [0-infinity], default: 500
# sizeHoles: size of small holes to remove [0-infinity], default: 200
# manualCorrections: manual corrections to connect skeleton [[x1, y1, x2, y2]], default: None
# imageType: define channel used for segmentation ['membrane', 'other'], default: 'membrane'
manualChanges:
    AFs:
        WT: 
            0: 
                R1: {} # leave empty if no changes should be added
                R2: {'sigmaTube': 4.0, 'manualCorrections': [[749, 527, 765, 552], [853, 496, 864, 506], [131, 259, 155, 236], [144, 755, 161, 752], [323, 373, 331, 373]], 'imageType': 'other', 'otsuMethod': 'multiotsu', 'sizeObjects': 200} # add all changes
                R3: {'manualThreshold': 105} # or add only specific ones
            
            
# -----------------------------------------------------------------------------
# Gauging parameters for cytoskeleton extraction (CytoSeg)
# -----------------------------------------------------------------------------
# Add gauging parameters for CytoSeg here to use for the extraction of filaments.
# Use CytoSeg GUI for optimal parameters: (Breuer et al., 2017; Nowak et al., 2020)
# Parameters must include: [sigma for Gaussian filter, sigma for tube filter, block size  for local 
# thresholding, size of small objects, factor for mean filament intensity]
parameters:
    AFs:
        WT: [1.4, 2.6, 53.0, 9.0, 0.4]
        act2-1act7-1: [1.4, 2.6, 103.0, 9.0, 0.4]
        

# -----------------------------------------------------------------------------
# Output
# -----------------------------------------------------------------------------
# Indicate here which output should be saved.
output: 
    globalDensities: True                   # global density and other global properties
    perpendicularDensities: True            # perpendicular mask densities
    circularDensities: True                 # circular mask densities
    polygonalDensities: True                # polygonal mask densities
    labeledCells: True                      # labeled image of segmented cells
    visibilityGraphs: True                  # visibility graphs of all segmented/selected cells
    cellContours: True                      # cell contours of all segmented/selected cells
    skeletonImageCells: True                # skeleton image of extracted cells
    junctions: True                         # position of tri-cellular junctions identified from cell membranes
    filteredCytoskeleton: True              # extracted filaments using CytoSeg
    membraneSegmentationOverlay: True       # overlay of segmented cells and their cell labels
    shapeResultsTable: True                 # results table with different parameters for each visibility graph
    
    