#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# -----------------------------------------------------------------------------
# Project info
# -----------------------------------------------------------------------------
project:
    name: 'Arabidopsis_Cotyledon'
    description: 'AF/MT density quantification in pavement cells'
    species: 'Arabidopsis thaliana'
    tissue: 'Cotyledons'
    stage: '48h'
    projection: 'SMP'

    
# -----------------------------------------------------------------------------
# Data structure
# -----------------------------------------------------------------------------
data: 
    root: 'Cotyledon'
    file_pattern: '*SMP.tif'
    channels: ['membrane', 'filament']
    targets: ['AFs', 'MTs']
    conditions: ['WT', 'act2-1act7-1']
    timepoints: 'single'

        
# -----------------------------------------------------------------------------
# Folder structure
# -----------------------------------------------------------------------------    
structure:
    targets: ['AFs', 'MTs']
    conditions: ['WT', 'act2-1act7-1']
    replicates: [] #auto-detect


# -----------------------------------------------------------------------------
# Image resolutions (µm/px)
# ----------------------------------------------------------------------------- 
resolutions:
    AFs: {WT: {'WT_1': 0.1806913250094863, 'WT_2': 0.1806913250094863, 'WT_3': 0.1806913250094863, 'WT_4': 0.1806913250094863, 'WT_5': 0.1806913250094863, 'WT_6': 0.1806913250094863}, act2-1act7-1: {'act2act7_1': 0.14485405953501845, 'act2act7_2': 0.14485405953501845, 'act2act7_3': 0.14485405953501845, 'act2act7_4': 0.14485405953501845, 'act2act7_5': 0.14485405953501845, 'act2act7_6': 0.14393459611952328, 'act2act7_7': 0.14393459611952328, 'act2act7_8': 0.14393459611952328}}
    MTs: {WT: {'WT_1': 0.1254028566770751, 'WT_2': 0.14462570866597246, 'WT_3': 0.14462570866597246, 'WT_4': 0.14462570866597246, 'WT_5': 0.14462570866597246, 'WT_6': 0.14462570866597246, 'WT_7': 0.14462570866597246, 'WT_8': 0.14462570866597246}, act2-1act7-1: {'act2act7_1': 0.14462570866597246, 'act2act7_2': 0.14462570866597246, 'act2act7_3': 0.14462570866597246, 'act2act7_4': 0.14462570866597246}}      
  
        
# -----------------------------------------------------------------------------
# Input channel data for pavement cell segmentation
# ----------------------------------------------------------------------------- 
inputChannel:
    AFs: {WT: {'WT_1': {'membrane': 'C1', 'filament': 'C2'}, 
               'WT_2': {'membrane': 'C1', 'filament': 'C2'}, 
               'WT_3': {'membrane': 'C2', 'filament': 'C2'}, 
               'WT_4': {'membrane': 'C2', 'filament': 'C2'}, 
               'WT_5': {'membrane': 'C1', 'filament': 'C2'}, 
               'WT_6': {'membrane': 'C1', 'filament': 'C2'}}, 
         act2-1act7-1: {'act2act7_1': {'membrane': 'C1', 'filament': 'C2'}, 
                        'act2act7_2': {'membrane': 'C1', 'filament': 'C2'}, 
                        'act2act7_3': {'membrane': 'C1', 'filament': 'C2'}, 
                        'act2act7_4': {'membrane': 'C1', 'filament': 'C2'}, 
                        'act2act7_5': {'membrane': 'C1', 'filament': 'C2'}, 
                        'act2act7_6': {'membrane': 'C1', 'filament': 'C2'}, 
                        'act2act7_7': {'membrane': 'C1', 'filament': 'C2'}, 
                        'act2act7_8': {'membrane': 'C1', 'filament': 'C2'}}}
    MTs: {WT: {'WT_1': {'membrane': 'C1', 'filament': 'C2'}, 
               'WT_2': {'membrane': 'C1', 'filament': 'C2'}, 
               'WT_3': {'membrane': 'C1', 'filament': 'C2'}, 
               'WT_4': {'membrane': 'C1', 'filament': 'C2'}, 
               'WT_5': {'membrane': 'C1', 'filament': 'C2'}, 
               'WT_6': {'membrane': 'C1', 'filament': 'C2'}, 
               'WT_7': {'membrane': 'C1', 'filament': 'C2'}, 
               'WT_8': {'membrane': 'C1', 'filament': 'C2'}}, 
        act2-1act7-1: {'act2act7_1': {'membrane': 'C1', 'filament': 'C2'}, 
                       'act2act7_2': {'membrane': 'C1', 'filament': 'C2'}, 
                       'act2act7_3': {'membrane': 'C1', 'filament': 'C2'}, 
                       'act2act7_4': {'membrane': 'C2', 'filament': 'C2'}}} 
             

# -----------------------------------------------------------------------------
# Selected cells for analysis
# -----------------------------------------------------------------------------
cells:
    AFs:
        WT:
            WT_1: '[1, 2, 7, 9, 10, 11, 12, 19, 26, 29]'
            WT_2: '[3, 4, 7, 13, 15, 16, 20, 26, 27, 28, 34, 35, 39, 46, 49]'
            WT_3: '[2, 3, 6, 7, 8, 9, 10, (11, 18, 26), 12, 16, 19, (20, 22), 23, 24, (27, 32), 31, 34, 37, 39, 41, 43, 28]'
            WT_4: '[2, 4, (6, 7, 15), 13, 14, 16, 20, 24, 25, 26, 27, 35, (34, 36), (37, 38, 41), (39, 40)]'
            WT_5: '[5, 11, 13, 14, 15, 16, 17, 20, 24, 28, 33, 35, 37, 39, 40, 42, 43, 45, 51, 54]'
            WT_6: '[6, 13, 20, 29, 30, 35, 37, 38, 41, 44, 45, 46, 48, 49, 54, 60, 62, 63, 64, 65, 70, 75, 78, 79, 83]'
        act2-1act7-1:
            act2act7_1: '[4, 8, 10, 13, 14, 15, 20, 21, 22]'
            act2act7_2: '[7, 8, 15, 17, 21, 22, 23, 24, 27, 28, 31, 33, 38, 39, 41, 42, (43, 63), 44, 48, 51, 52, 53, 55, 58, 59, 64, 67, 75, 76]'
            act2act7_3: '[1, 2, 6, 7, 8, 9, 13, 17, 19, 20, 21, 22, 23, 25]'
            act2act7_4: '[7, 8, 9, 10, 13, 17, 18, 19, 21, 16, 23, 26, 30, 31, 34, 35, 36, 38, 46, 47, 48, 49, 50, 51, 52, 54, 55, 59, 61, 63, 64, 66, 74, 78, 80]'
            act2act7_5: '[1, 7, 13, 14, 15, 17, 18, 19, 21, 23, 24, 25, 26, 29, 31, 33, 35, 36, 39, 45, 46, 53, 54, 55, 56, 57, 58, 60, 62, 66, 68, 69, 71, 70, 80, 78]'
            act2act7_6: '[2, 3, 4, 6, 7, 8, 9, 10, 15, 16, 18, 20, 22, 24, 26, 28, 31, 32, 33, 34, 38, 40, 41, 42, 44, 47, 48, 59, 61, 68, 70, 73, 74, 75, 84]'
            act2act7_7: '[4, 5, 16, 13, (14, 37), 15, 17, 20, 25, 28, 30, 32, 34, 35, 42, 44, 49, 50, 51, 53, 54, 56, 57, 67, 63]'
            act2act7_8: '[6, 8, 10, 11, 13, 15, 16, 20, 24, 26, 27, 31, 33, 34, 37, 40, 41, 42, 43, 44, 52, 57, 58, 59, 60, 61]'
    MTs:
        WT:
            WT_1: '[3, 5, 7, 9, 10, 11, 12, 13, 15, 16, 17, 21, 24, 25, 26, 28, 29, 32, 33, 34, 35, 36, 37, 38, 40, 41, 43, 44, 45, 46, 48, 49, 50, 51, 52, 55, 57, 61, 63, 65, 67]'
            WT_2: '[5, 7, 8, 10, 13, 14, 16, 18, 21, 22, 23, 24, 30, 31, 32, 33, 34, 35, 50, 51, 57, 58, 59, 60, 62, 63, 66, 69, 72, 80, 78, 79, 84, 81, 88, 85]'
            WT_3: '[1, 2, 3, 7, 12, 17, (18, 23), 19, 22, 24, 25, 28, 29, 30, 32, 36, 38, 43, 44, 45, 49, 52, 53, 54, 55, 66, 65, 64]'
            WT_4: '[1, 3, 9, 11, 15, 16, 18, 19, 20, 22, 24, 26, 30, 32, 41, 42, 44, 49, 51, 52, 55, 56, 58, 59, 63, 65, 67, 68, 73, 74, 75, 84, 87, 88, 90, 93, 103, 106, 118, 100, 112, 107, 99, 95]'
            WT_5: '[4, 5, 10, 11, 16, 17, 18, 20, 21, 23, 27, 28, 29, 30, 31, 33, 38, 41, 43, 48, 51, 52, 53, 55, 58, 59, 61, 64, 65, 66, 67, 68, 72, 83, 76, 82, 79, 84, 80, 92]'
            WT_6: '[3, 4, 5, 9, 11, 13, 8, 16, 18, 19, 20, 23, 36, 43, 40, 39, 38, 42, 45, 48, 49, 50, 51, 52, 58, 60, 67, 64, 70]'
            WT_7: '[1, 2, 3, 5, 7, 13, 14, 15, 18, 19, 20, 22, 24, 27, 32, 33, 36, 43, 44, 47, 48, 49, 51, 52, 56, 59, 60, 61, 64, 69, 71, 77, 86, 92, 102, 89, 81, 98, 107, 90]'
            WT_8: '[3, 6, 11, 12, 13, 15, 16, 20, 21, 25, 26, 28, 31, 32, 34, 35, 38, 39, 41, 43, 45, 49, 54, 56, 57, 58, 60, 64, 65, 72, 75, 73, 78, 70, 80, 81, 98, 97, 88, 102, 86, 82, 95, 100, 104, 93, 90]'
        act2-1act7-1:
            act2act7_1: '[5, 6, 7, 8, 11, 18, 19, 20, 22, 24, 25, 27, 29, 30, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 52, 59, 60, 61]'
            act2act7_2: '[12, 24, 29, 34, 39, 38, 41, 40, 48, 53, 51, 54, 56, 52, 55, 57, 69, 68, 72, 78, 77, 82, 73, 86]'
            act2act7_3: '[3, 5, 7, 11, 12, 14, 15, 16, 17, 19, 22, 23, 24, 25, 26, 27, 28, 31, 35, 33, 32]'
            act2act7_4: '[(13, 12, 27, 14, 29, 30), (68, 72, 69, 67, 61, 63, 60)]'
  
            
# -----------------------------------------------------------------------------
# Manual changes for pavement cell segmentation
# -----------------------------------------------------------------------------
manualChanges:
    AFs:
        WT:
            WT_1: {}
            WT_2: {'manualThreshold': 75, 'sizeObjects': 5000}
            WT_3: {'sigmaTube': 4.0, 'manualCorrections': [[749, 527, 765, 552], [853, 496, 864, 506], [131, 259, 155, 236], [144, 755, 161, 752], [323, 373, 331, 373]], 'imageType': 'other', 'otsuMethod': 'multiotsu', 'sizeObjects': 200} 
            WT_4: {'sigmaTube': 4.0, 'manualCorrections': [[35, 270, 47, 270], [352, 338, 352, 347], [752, 664, 758, 653], [453, 829, 478, 830]], 'imageType': 'other', 'otsuMethod': 'multiotsu', 'sizeObjects': 200}           
            WT_5: {}
            WT_6: {'manualThreshold': 70, 'manualCorrections': [[116, 720, 123, 714]]}
        act2-1act7-1:
            act2act7_1: {'manualThreshold': 75, 'manualCorrections': [[241, 902, 250, 894]]}
            act2act7_2: {'manualThreshold': 70, 'sizeObjects': 5000}
            act2act7_3: {}
            act2act7_4: {'manualThreshold': 75, 'manualCorrections': [[492, 781, 496, 776]]}
            act2act7_5: {}
            act2act7_6: {'manualThreshold': 65, 'manualCorrections': [[556, 558, 560, 566], [602, 562, 614, 565], [602, 520, 617, 559], [131, 378, 135, 394]]}
            act2act7_7: {'manualThreshold': 70, 'manualCorrections': [[528, 374, 536, 379], [368, 584, 376, 581], [973, 744, 1002, 741]]}
            act2act7_8: {'manualThreshold': 80, 'manualCorrections': [[783, 798, 780, 805]]}
    MTs: 
        WT:
            WT_1: {'manualThreshold': 92, 'manualCorrections': [[710, 568, 709, 582]]}
            WT_2: {'manualThreshold': 75}
            WT_3: {'manualThreshold': 60, 'sizeObjects': 5000, 'manualCorrections': [[685, 519, 693, 544], [894, 824, 899, 822]]}
            WT_4: {}
            WT_5: {}
            WT_6: {}
            WT_7: {'manualThreshold': 75}
            WT_8: {}
        act2-1act7-1:
            act2act7_1: {'manualThreshold': 80}
            act2act7_2: {'manualThreshold': 70}
            act2act7_3: {}
            act2act7_4: {'imageType': 'other', 'sizeObjects': 200}
            
            
# -----------------------------------------------------------------------------
# Gauging parameters for cytoskeleton extraction (CytoSeg)
# -----------------------------------------------------------------------------
parameters:
    AFs:
        WT: [1.4, 2.6, 53.0, 9.0, 0.4]
        act2-1act7-1: [1.4, 2.6, 103.0, 9.0, 0.4]
    MTs: 
        WT: [1.4, 2.0, 53.0, 9.0, 0.2]
        act2-1act7-1: [1.4, 2.0, 53.0, 9.0, 0.2]


# -----------------------------------------------------------------------------
# Output
# -----------------------------------------------------------------------------
output: 
    globalDensities: True
    perpendicularDensities: True
    circularDensities: True
    polygonalDensities: True
    labeledCells: True
    visibilityGraphs: True
    cellContours: True
    skeletonImageCells: True
    junctions: True
    filteredCytoskeleton: True
    membraneSegmentationOverlay: True
    shapeResultsTable: True
    
    